<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Auth extends CI_Controller
{

    public function __construct()
    {
        parent::__construct();
        $this->load->model('User');
        $this->load->library(['form_validation', 'session', 'email']);
        $this->load->library('session');
        $this->load->helper('url');
        $this->load->helper('form');
        $this->load->library('email');
    }

    private function send_email_via_curl($to, $subject, $body, $name = '')
    {
        $post = [
            'inquire_now' => $name,             
            'replyto'     => $to,                
            'contsubj'    => $subject,           
            'contbody'    => $body               
        ];

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://aws.erav.lk/Temp/bf360/eravawsmail.php"); 
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

        $response = curl_exec($ch);
        $error    = curl_error($ch);
        curl_close($ch);

        return true;
    }


    public function index()
    {
        $this->load->view('pages/signin');
    }

    public function signup()
    {
        $this->load->view('pages/signup');
    }

    public function register_user()
    {
        $this->form_validation->set_rules('name', 'Name', 'required|trim|min_length[2]|max_length[100]');
        $this->form_validation->set_rules('email', 'Email', 'required|valid_email|is_unique[users.email]|max_length[100]');
        $this->form_validation->set_rules('password', 'Password', 'required|min_length[6]|max_length[255]');
        $this->form_validation->set_rules('confirm_password', 'Confirm Password', 'required|matches[password]');

        $this->form_validation->set_message('is_unique', 'This {field} is already registered.');
        $this->form_validation->set_message('matches', 'Password and Confirm Password do not match.');

        if ($this->form_validation->run() == FALSE) {
            $this->session->set_flashdata('validation_errors', validation_errors());
            redirect('Auth/signup');
        } else {

            $verification_code = rand(100000, 999999);

            $this->session->set_userdata('pending_user', [
                'name' => $this->input->post('name'),
                'email' => $this->input->post('email'),
                'password' => password_hash($this->input->post('password'), PASSWORD_DEFAULT),
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s')
            ]);
            $this->session->set_userdata('verification_code', $verification_code);

            $subject = 'Email Verification - eRav Budget Management';
            $body = "
    Hello {$this->input->post('name')},<br><br>
    Your verification code is: <b>$verification_code</b><br><br>
    <small style='color:gray;'>Generated by eRav Budget Management System</small>
";

            if ($this->send_email_via_curl($this->input->post('email'), $subject, $body, $this->input->post('name'))) {
                $this->session->set_flashdata('success', 'Verification code sent to your email. Please enter it below.');
                redirect('Auth/verify_email');
            } else {
                $this->session->set_flashdata('error', 'Failed to send verification email. Try again.');
                redirect('Auth/signup');
            }
        }
    }

    public function verify_email()
    {
        if ($this->input->method() === 'post') {
            $entered_code = $this->input->post('code');
            $session_code = $this->session->userdata('verification_code');
            $pending_user = $this->session->userdata('pending_user');

            if ($entered_code == $session_code && $pending_user) {
                $this->User->insert_user($pending_user);

                $this->session->unset_userdata('pending_user');
                $this->session->unset_userdata('verification_code');

                $this->session->set_flashdata('success', 'Email verified! You can now sign in.');
                redirect('Auth');
            } else {
                $this->session->set_flashdata('error', 'Invalid verification code.');
                redirect('Auth/verify_email');
            }
        } else {
            $this->load->view('pages/verify_email');
        }
    }

    public function login()
    {
        $email = $this->input->post('email');
        $password = $this->input->post('password');

        $user = $this->User->get_user_by_email($email);

        if ($user && password_verify($password, $user['password'])) {
            $this->session->set_userdata('user_id', $user['id']);
            $this->session->set_userdata('user_name', $user['name']);
            redirect('Dashboard');
        } else {
            $this->session->set_flashdata('error', 'Invalid email or password.');
            redirect('Auth');
        }
    }

    public function request_password_reset()
    {
        if ($this->input->method() === 'post') {
            $email = $this->input->post('email');
            $user = $this->User->get_user_by_email($email);

            if (!$user) {
                $this->session->set_flashdata('error', 'This email is not registered.');
                redirect('Auth/request_password_reset');
            }

            $verification_code = rand(100000, 999999);

            $this->session->set_userdata('reset_email', $email);
            $this->session->set_userdata('reset_code', $verification_code);

            $this->load->library('email');
            $subject = 'Password Reset Verification Code';
            $body = "
    Hello,<br><br>
    Your password reset verification code is: <b>$verification_code</b><br><br>
    <small style='color:gray;'>Generated by eRav Budget Management System</small>
";

            if ($this->send_email_via_curl($email, $subject, $body)) {
                $this->session->set_flashdata('success', 'Verification code sent. Check your email.');
                redirect('Auth/verify_reset_code');
            } else {
                $this->session->set_flashdata('error', 'Failed to send email. Try again.');
                redirect('Auth/request_password_reset');
            }
        } else {
            $this->load->view('pages/request_password_reset');
        }
    }

    public function verify_reset_code()
    {
        if ($this->input->method() === 'post') {
            $entered_code = $this->input->post('code');
            $session_code = $this->session->userdata('reset_code');
            $email = $this->session->userdata('reset_email');

            if ($entered_code == $session_code) {
                $this->session->set_userdata('allow_password_reset', true);
                redirect('Auth/change_password');
            } else {
                $this->session->set_flashdata('error', 'Invalid verification code.');
                redirect('Auth/verify_reset_code');
            }
        } else {
            $this->load->view('pages/verify_reset_code');
        }
    }

    public function change_password()
    {
        if (!$this->session->userdata('allow_password_reset')) {
            redirect('Auth');
        }

        if ($this->input->method() === 'post') {
            $new_password = $this->input->post('password');
            $confirm_password = $this->input->post('confirm_password');
            $email = $this->session->userdata('reset_email');

            if ($new_password !== $confirm_password) {
                $this->session->set_flashdata('error', 'Passwords do not match.');
                redirect('Auth/change_password');
            }

            $hashed = password_hash($new_password, PASSWORD_DEFAULT);
            $this->db->where('email', $email)->update('users', ['password' => $hashed]);

            $this->session->unset_userdata('reset_email');
            $this->session->unset_userdata('reset_code');
            $this->session->unset_userdata('allow_password_reset');

            $this->session->set_flashdata('success', 'Password changed successfully! Please login.');
            redirect('Auth');
        } else {
            $this->load->view('pages/change_password');
        }
    }


    public function logout()
    {
        $this->session->unset_userdata('user_id');
        $this->session->unset_userdata('user_name');
        $this->session->sess_destroy();
        redirect('Auth');
    }
}
